import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateBank} from '../dist/bank.js';
import {POINTS,createGame,makeRound,selectAnswer,revealAnswer,nextQuestion,stopGame,useAid,restoreGame} from '../dist/engine.js';
const bank=Array.from({length:500},(_,i)=>({id:`fixture${i}`,factKey:`f${i}`,family:`family${i}`,band:1+Math.floor(i/100),topic:`tema${i%7}`,prompt:`Prueba ${i}`,options:[`Correcta${i}`,'B','C','D'],answer:0,hint:'Pista de prueba',explanation:'Explicación de prueba'}));
const rng=()=>{let x=23;return ()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296;};};
const winOne=g=>{selectAnswer(g,g.round[g.index].answer);assert.equal(revealAnswer(g),true);};
test('Escalera exacta de ALEPH',()=>assert.deepEqual([...POINTS],[0,100,200,300,500,1000,1500,2500,4000,6500,10000,15000,25000,40000,65000,100000]));
test('15 preguntas, 3 por banda, distintas y con respuesta bien barajada',()=>{const g=createGame(bank,new Set(),rng());assert.deepEqual(g.round.map(q=>q.band),[1,1,1,2,2,2,3,3,3,4,4,4,5,5,5]);assert.equal(new Set(g.round.map(q=>q.family)).size,15);for(const q of g.round)assert.equal(q.options[q.answer],bank.find(o=>o.id===q.id).options[0]);});
for(let n=0;n<15;n++)test(`Fallar la pregunta ${n+1} conserva el seguro correcto`,()=>{const g=createGame(bank);for(let i=0;i<n;i++){winOne(g);nextQuestion(g);}selectAnswer(g,(g.round[g.index].answer+1)%4);assert.equal(revealAnswer(g),false);assert.equal(g.score,n>=10?10000:n>=5?1000:0);assert.equal(g.outcome,'miss');assert.equal(selectAnswer(g,0),false);assert.ok(restoreGame(g,bank));nextQuestion(g);assert.equal(g.phase,'result');assert.ok(restoreGame(g,bank));});
test('Quince aciertos dan 100000 y cierran la partida',()=>{const g=createGame(bank);for(let i=0;i<15;i++){winOne(g);nextQuestion(g);}assert.equal(g.outcome,'win');assert.equal(g.score,100000);assert.equal(g.phase,'result');assert.ok(restoreGame(g,bank));});
test('Plantarse conserva todo lo ganado en cada peldaño',()=>{for(let n=0;n<15;n++){const g=createGame(bank);for(let i=0;i<n;i++){winOne(g);nextQuestion(g);}assert.equal(stopGame(g),true);assert.equal(g.score,POINTS[n]);assert.equal(g.outcome,'stop');assert.ok(restoreGame(g,bank));}});
test('50:50 conserva respuesta, descarta dos errores y se usa una vez',()=>{const g=createGame(bank);assert.ok(useAid(g,'half',bank));assert.equal(g.hidden.length,2);assert.ok(!g.hidden.includes(g.round[0].answer));assert.equal(useAid(g,'half',bank),false);assert.equal(selectAnswer(g,g.hidden[0]),false);});
test('Pista y 50:50 se mantienen al cambiar, con los tres comodines gastados',()=>{const g=createGame(bank);const old=g.round[0];useAid(g,'hint',bank);useAid(g,'half',bank);selectAnswer(g,g.round[0].answer);assert.ok(useAid(g,'swap',bank));assert.notEqual(g.round[0].id,old.id);assert.equal(g.round[0].band,old.band);assert.equal(g.selected,null);assert.equal(g.hint,true);assert.equal(g.hidden.length,2);assert.ok(!g.hidden.includes(g.round[0].answer));assert.deepEqual(g.aids,{half:false,hint:false,swap:false});assert.ok(restoreGame(g,bank));});
test('Cambiar no usa una familia presente ni la pregunta retirada',()=>{const g=createGame(bank);const families=new Set(g.round.map(q=>q.family));useAid(g,'swap',bank);assert.ok(!families.has(g.round[0].family));assert.equal(g.retired.length,1);});
test('Las ayudas de una pregunta no afectan a la siguiente',()=>{const g=createGame(bank);useAid(g,'hint',bank);useAid(g,'half',bank);winOne(g);nextQuestion(g);assert.equal(g.hint,false);assert.deepEqual(g.hidden,[]);assert.equal(g.aids.hint,false);assert.equal(g.aids.half,false);});
test('No se gastan comodines inválidos ni durante la explicación',()=>{const g=createGame(bank);assert.equal(useAid(g,'toString',bank),false);assert.equal(useAid(g,'bad',bank),false);winOne(g);assert.equal(useAid(g,'hint',bank),false);assert.equal(g.aids.hint,true);});
test('Treinta partidas completas sin repetir preguntas de un banco suficiente',()=>{const seen=new Set(),random=rng();for(let i=0;i<30;i++){const round=makeRound(bank,seen,random);for(const q of round){assert.ok(!seen.has(q.id));seen.add(q.id);}}assert.equal(seen.size,450);});
test('Banco agotado permite repetir sin duplicar dentro de la partida',()=>{const round=makeRound(bank,new Set(bank.map(q=>q.id)));assert.equal(new Set(round.map(q=>q.id)).size,15);});
test('Se rechazan guardados corruptos y datos que ya no existen',()=>{const g=createGame(bank);assert.equal(restoreGame({...g,index:99},bank),null);assert.equal(restoreGame({...g,score:100000},bank),null);assert.equal(restoreGame(g,bank.slice(0,100)),null);assert.equal(restoreGame(null,bank),null);});
test('Recuperación exacta con respuesta elegida y comodines utilizados',()=>{const g=createGame(bank);useAid(g,'hint',bank);useAid(g,'half',bank);selectAnswer(g,g.round[0].answer);assert.deepEqual(restoreGame(JSON.parse(JSON.stringify(g)),bank),g);});

test('Cada etapa mezcla conceptos, historia y sociedad cuando hay alternativas nuevas',()=>{const b=bank.map((q,i)=>({...q,track:['conceptos','historia','sociedad'][i%3]}));for(let n=0;n<100;n++){const r=makeRound(b);for(let band=1;band<=5;band++)assert.equal(new Set(r.filter(q=>q.band===band).map(q=>q.track)).size,3);}});

test('Evitar repetición tiene prioridad sobre la mezcla de ámbitos',()=>{const b=bank.map((q,i)=>({...q,track:['conceptos','historia','sociedad'][i%3]}));const seen=new Set(b.filter(q=>q.track!=='conceptos').map(q=>q.id));const r=makeRound(b,seen);assert.ok(r.every(q=>q.track==='conceptos'&&!seen.has(q.id)));});

test('No se recupera una clave correcta codificada como texto o booleano',()=>{for(const invalid of ['0',false,null,4,-1,0.5]){const g=createGame(bank);g.round[0].answer=invalid;assert.equal(restoreGame(g,bank),null);}});
test('Cada partida tiene identidad propia aunque comience en el mismo milisegundo',()=>{const a=createGame(bank),b=createGame(bank);assert.ok(a.id);assert.notEqual(a.id,b.id);});

test('El historial recuperado debe conservar el orden de respuestas mostrado',()=>{const g=createGame(bank,new Set(),rng());winOne(g);const saved=JSON.parse(JSON.stringify(g));const h=saved.history[0],correctText=h.question.options[h.question.answer];h.question.options.reverse();h.question.answer=h.question.options.indexOf(correctText);h.selected=h.question.answer;saved.selected=h.selected;assert.equal(restoreGame(saved,bank),null);assert.ok(restoreGame(JSON.parse(JSON.stringify(g)),bank));});

test('Una fecha de revisión como array se rechaza antes de mostrar la fuente',()=>{const real=JSON.parse(fs.readFileSync(new URL('../dist/questions.json',import.meta.url),'utf8'));real[0].reviewedAt=[real[0].reviewedAt];assert.throws(()=>validateBank(real));});
test('Las fuentes opcionales de pistas requieren HTTPS y un título',()=>{const b=JSON.parse(fs.readFileSync(new URL('../dist/questions.json',import.meta.url),'utf8'));for(const patch of [{hintSource:'javascript:alert(1)',hintSourceTitle:'Pista'},{hintSource:'https://example.com',hintSourceTitle:''}]){const altered=structuredClone(b);Object.assign(altered[0],patch);assert.throws(()=>validateBank(altered));}const valid=structuredClone(b);Object.assign(valid[0],{hintSource:'https://example.com',hintSourceTitle:'Pista documentada'});assert.equal(validateBank(valid),valid);});
