const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../dist'),artifacts=path.join(__dirname,'artifacts/usability');
const report={checks:[],accessibility:[],errors:[]};let browser,server;
const check=(name,pass)=>{report.checks.push({name,pass:!!pass});assert.ok(pass,name);};
async function accessible(p,label){await p.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const a=await p.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return {violations:r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>v.id)}});report.accessibility.push({label,...a});check(label+' sin infracciones automáticas',!a.violations.length);}
async function modalLayout(p,label){const r=await p.evaluate(()=>{const title=document.querySelector('#modal-title'),scroll=document.querySelector('.dialog-scroll'),close=document.querySelector('#close-modal').getBoundingClientRect();return {titleScrollable:title.scrollHeight>title.clientHeight+1,overflow:scroll.scrollWidth>scroll.clientWidth+1,bodyOverflow:getComputedStyle(document.querySelector('#modal-body')).overflowY,closeVisible:close.top>=0&&close.bottom<=innerHeight,scrollable:scroll.scrollHeight>scroll.clientHeight};});check(label+' título sin scroll separado',!r.titleScrollable);check(label+' contenido sin desborde horizontal',!r.overflow);check(label+' cuerpo integrado en scroll único',r.bodyOverflow==='visible');check(label+' cierre visible',r.closeVisible);}
(async()=>{try{
 fs.mkdirSync(artifacts,{recursive:true});
 let url=process.env.QA_BASE_URL;
 if(!url){server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}/`;}
 browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));
 await p.goto(url);await p.locator('[data-action=start]').waitFor();
 check('Portada condiciona el guardado a la disponibilidad', (await p.locator('.personal-best').innerText()).includes('si el navegador permite guardar datos'));
 const image=await p.locator('meta[property="og:image"]').getAttribute('content');check('Imagen social con URL pública',image==='https://elcontemplador.github.io/reto-estrategia-ia/assets/social-card.png');
 const png=await p.request.get(new URL('assets/social-card.png',url).href),bytes=await png.body();check('Imagen social 1200 × 630 disponible',png.ok()&&bytes.readUInt32BE(16)===1200&&bytes.readUInt32BE(20)===630);
 for(const [width,height] of [[320,844],[390,844],[844,390]]){
  await p.setViewportSize({width,height});await p.evaluate(()=>document.documentElement.style.fontSize='200%');
  await p.locator('#rules').click();await modalLayout(p,`Reglas ${width} texto 200%`);
  await p.screenshot({path:path.join(artifacts,`reglas-${width}-200.png`)});
  await p.locator('.dialog-scroll').focus();await p.keyboard.press('End');await p.waitForFunction(()=>{const s=document.querySelector('.dialog-scroll');return s.scrollTop>0;});check(`Reglas ${width} se recorren con teclado`,await p.locator('.dialog-scroll').evaluate(e=>e.scrollTop>0));
  await p.keyboard.press('Escape');check('Escape cierra reglas',!await p.locator('#modal').isVisible());
  await p.locator('#rules').click();check('Reapertura devuelve al comienzo',await p.locator('.dialog-scroll').evaluate(e=>e.scrollTop===0));await p.keyboard.press('Escape');
 }
 await p.setViewportSize({width:320,height:844});await p.locator('#method').click();await modalLayout(p,'Fuentes texto 200%');
 const sourceCount=new Set(JSON.parse(fs.readFileSync(path.join(root,'questions.json'),'utf8')).map(q=>q.source.split('#')[0])).size;
 check('Inventario cuenta páginas y no anclas',await p.locator('.source-list li').count()===sourceCount);await accessible(p,'Fuentes texto 200%');await p.keyboard.press('Escape');
 await p.evaluate(()=>document.documentElement.style.fontSize='');await p.setViewportSize({width:390,height:844});await p.locator('[data-action=start]').click();await p.locator('.question-title').waitFor();
 check('Acceso a comodines visible antes de las respuestas',await p.locator('[data-action=aids]').evaluate(e=>e.getBoundingClientRect().bottom<document.querySelector('.answers').getBoundingClientRect().top));
 check('Contador inicial de tres comodines',(await p.locator('[data-action=aids]').innerText()).includes('3 comodines disponibles'));
 await p.screenshot({path:path.join(artifacts,'pregunta-390.png'),fullPage:true});await p.locator('[data-action=aids]').click();check('Acceso lleva foco al primer comodín',await p.locator('[data-aid=half]').evaluate(e=>e===document.activeElement));
 check('Ayudas anteriores a confirmación en orden de teclado',await p.locator('.aids').evaluate(e=>!!(e.compareDocumentPosition(document.querySelector('.answer-actions'))&Node.DOCUMENT_POSITION_FOLLOWING)));
 await p.locator('[data-aid=half]').click();await p.waitForFunction(()=>document.querySelector('[data-action=aids]').textContent.includes('2 comodines'));await p.locator('[data-aid=hint]').click();await p.waitForFunction(()=>document.querySelector('[data-action=aids]').textContent.includes('1 comodín disponible'));check('Contador singular tras dos usos',true);
 await p.locator('[data-aid=swap]').click();await p.waitForFunction(()=>document.querySelector('[data-action=aids]').disabled);check('Contador avisa de ayudas agotadas',(await p.locator('[data-action=aids]').innerText()).includes('Comodines utilizados'));
 await accessible(p,'Pregunta con ayudas utilizadas');
 const answer=await p.evaluate(()=>{const g=JSON.parse(localStorage.getItem('estrategia-quiz-v3')).game;return g.round[g.index].answer});await p.locator(`[data-answer="${answer}"]`).click();await p.locator('[data-action=confirm]').click();await p.locator('.feedback').waitFor();
 await p.locator('.feedback .source-detail summary').click();await p.locator('[data-report]').click();await p.setViewportSize({width:320,height:844});await p.evaluate(()=>document.documentElement.style.fontSize='200%');await modalLayout(p,'Referencia texto 200%');await p.locator('#report-comment').fill('Prueba local; no se envía ningún aviso.');await p.keyboard.press('Escape');await p.locator('[data-report]').click();check('Referencia conserva borrador al reabrir',(await p.locator('#report-comment').inputValue()).startsWith('Prueba local'));await p.keyboard.press('Escape');
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Blocked','SecurityError')}});const bp=await blocked.newPage();await bp.goto(url);await bp.locator('[data-action=start]').waitFor();check('Portada sin escritura no promete guardado incondicional',(await bp.locator('.personal-best').innerText()).includes('si el navegador permite'));await bp.locator('[data-action=start]').click();await bp.locator('.save-warning').waitFor();check('Sin escritura se avisa al empezar',(await bp.locator('.save-warning').innerText()).includes('no se está guardando'));await blocked.close();
 check('Sin errores JavaScript',report.errors.length===0);report.status='passed';
}catch(e){report.status='failed';report.failure=e.stack;process.exitCode=1;}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));fs.mkdirSync(artifacts,{recursive:true});fs.writeFileSync(path.join(artifacts,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}})();
